- Target: nmaguiar/netutils:build-lite (alpine 3.23.0_alpha20250612)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-58050
    PkgID: pcre2@10.45-r0
    PkgName: pcre2
    PkgIdentifier:
      PURL: pkg:apk/alpine/pcre2@10.45-r0?arch=x86_64&distro=3.23.0_alpha20250612
      UID: 7cd9f4230bb0c57
    InstalledVersion: 10.45-r0
    FixedVersion: 10.46-r0
    Status: fixed
    Layer:
      Digest: sha256:ad7e4b18dd8035e2631cd065ee440218372c1fcb65e6bf84aff147ad91ed1d63
      DiffID: sha256:97bde9317e374908a30c249b92e0835c6d41ed7811d6a05a7bda126dd1c00566
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-58050
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: The PCRE2 library is a set of C functions that implement regular expre ...
    Description: The PCRE2 library is a set of C functions that implement regular expression pattern matching. In version 10.45, a heap-buffer-overflow read vulnerability exists in the PCRE2 regular expression matching engine, specifically within the handling of the (*scs:...) (Scan SubString) verb when combined with (*ACCEPT) in src/pcre2_match.c. This vulnerability may potentially lead to information disclosure if the out-of-bounds data read during the memcmp affects the final match result in a way observable by the attacker. This issue has been resolved in version 10.46.
    Severity: UNKNOWN
    CweIDs:
    - CWE-122
    - CWE-125
    References:
    - https://github.com/PCRE2Project/pcre2/commit/a141712e5967d448c7ce13090ab530c8e3d82254
    - https://github.com/PCRE2Project/pcre2/releases/tag/pcre2-10.46
    - https://github.com/PCRE2Project/pcre2/security/advisories/GHSA-c2gv-xgf5-5cc2
    PublishedDate: '2025-08-27T19:15:37.56Z'
    LastModifiedDate: '2025-08-27T20:15:33.8Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
