- Target: nmaguiar/netutils:latest (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-23217
    PkgName: mitmproxy
    PkgPath: opt/mitmproxy/lib/python3.12/site-packages/mitmproxy-11.0.2.dist-info/METADATA
    PkgIdentifier:
      PURL: pkg:pypi/mitmproxy@11.0.2
      UID: 6b369dbabbb32323
    InstalledVersion: 11.0.2
    FixedVersion: 11.1.2
    Status: fixed
    Layer:
      Digest: sha256:00f19dd58a1529b2043f694b571828acf17cac3b0747933a3a0e57dc650ff17d
      DiffID: sha256:8023ce50c72afb3634be2f5a190d34b330bfd9ebd0f77f8d1342584189737ee5
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-23217
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory pip
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip
    Title: mitmproxy is a interactive TLS-capable intercepting HTTP proxy for pen ...
    Description: mitmproxy is a interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers and mitmweb is a web-based interface for mitmproxy. In mitmweb 11.1.1 and below, a malicious client can use mitmweb's proxy server (bound to `*:8080` by default) to access mitmweb's internal API (bound to `127.0.0.1:8081` by default). In other words, while the cannot access the API directly, they can access the API through the proxy. An attacker may be able to escalate this SSRF-style access to remote code execution. The mitmproxy and mitmdump tools are unaffected. Only mitmweb is affected. This vulnerability has been fixed in mitmproxy 11.1.2 and above. Users are advised to upgrade. There are no known workarounds for this vulnerability.
    Severity: HIGH
    CweIDs:
    - CWE-288
    - CWE-441
    VendorSeverity:
      ghsa: 3
    References:
    - https://en.wikipedia.org/wiki/Server-side_request_forgery
    - https://github.com/mitmproxy/mitmproxy
    - https://github.com/mitmproxy/mitmproxy/blob/main/CHANGELOG.md
    - https://github.com/mitmproxy/mitmproxy/blob/main/CHANGELOG.md#06-february-2025-mitmproxy-1112
    - https://github.com/mitmproxy/mitmproxy/commit/fa89055e196d953f11fd241e36ee37858993486a
    - https://github.com/mitmproxy/mitmproxy/security/advisories/GHSA-wg33-5h85-7q5p
    - https://nvd.nist.gov/vuln/detail/CVE-2025-23217
    PublishedDate: '2025-02-06T18:15:32.667Z'
    LastModifiedDate: '2025-02-06T18:15:32.667Z'
