- Target: nmaguiar/netutils:build-lite (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-4947
    PkgID: curl@8.13.0-r1
    PkgName: curl
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl@8.13.0-r1?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 852bc70963a76a45
    InstalledVersion: 8.13.0-r1
    FixedVersion: 8.14.0-r0
    Status: fixed
    Layer:
      Digest: sha256:1b256764d0e3457b2f7d15a1b7d9f50bc17b441f548cbfda2141f820f345589c
      DiffID: sha256:47f369694a4f622382553dd6634511eea449cb3e28b1b596262f88b91ef682c0
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4947
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'libcurl: curl: QUIC certificate check skip with wolfSSL'
    Description: libcurl accidentally skips the certificate verification for QUIC connections when connecting to a host specified as an IP address in the URL. Therefore, it does not detect impostors or man-in-the-middle attacks.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 6.5
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/28/4
    - https://access.redhat.com/security/cve/CVE-2025-4947
    - https://curl.se/docs/CVE-2025-4947.html
    - https://curl.se/docs/CVE-2025-4947.json
    - https://hackerone.com/reports/3150884
    - https://nvd.nist.gov/vuln/detail/CVE-2025-4947
    - https://www.cve.org/CVERecord?id=CVE-2025-4947
    PublishedDate: '2025-05-28T07:15:24.78Z'
    LastModifiedDate: '2025-05-28T15:01:30.72Z'
  - VulnerabilityID: CVE-2025-5025
    PkgID: curl@8.13.0-r1
    PkgName: curl
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl@8.13.0-r1?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 852bc70963a76a45
    InstalledVersion: 8.13.0-r1
    FixedVersion: 8.14.0-r0
    Status: fixed
    Layer:
      Digest: sha256:1b256764d0e3457b2f7d15a1b7d9f50bc17b441f548cbfda2141f820f345589c
      DiffID: sha256:47f369694a4f622382553dd6634511eea449cb3e28b1b596262f88b91ef682c0
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-5025
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: libcurl: QUIC Certificate Pinning Bypass'
    Description: libcurl supports *pinning* of the server certificate public key for HTTPS transfers. Due to an omission, this check is not performed when connecting with QUIC for HTTP/3, when the TLS backend is wolfSSL. Documentation says the option works with wolfSSL, failing to specify that it does not for QUIC and HTTP/3. Since pinning makes the transfer succeed if the pin is fine, users could unwittingly connect to an impostor server without noticing.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.8
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/28/5
    - https://access.redhat.com/security/cve/CVE-2025-5025
    - https://curl.se/docs/CVE-2025-5025.html
    - https://curl.se/docs/CVE-2025-5025.json
    - https://hackerone.com/reports/3153497
    - https://nvd.nist.gov/vuln/detail/CVE-2025-5025
    - https://www.cve.org/CVERecord?id=CVE-2025-5025
    PublishedDate: '2025-05-28T07:15:24.91Z'
    LastModifiedDate: '2025-05-30T17:15:30.2Z'
  - VulnerabilityID: CVE-2025-4947
    PkgID: curl-doc@8.13.0-r1
    PkgName: curl-doc
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl-doc@8.13.0-r1?arch=x86_64&distro=3.22.0_alpha20250108
      UID: d81fa5afdf86609d
    InstalledVersion: 8.13.0-r1
    FixedVersion: 8.14.0-r0
    Status: fixed
    Layer:
      Digest: sha256:1b256764d0e3457b2f7d15a1b7d9f50bc17b441f548cbfda2141f820f345589c
      DiffID: sha256:47f369694a4f622382553dd6634511eea449cb3e28b1b596262f88b91ef682c0
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4947
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'libcurl: curl: QUIC certificate check skip with wolfSSL'
    Description: libcurl accidentally skips the certificate verification for QUIC connections when connecting to a host specified as an IP address in the URL. Therefore, it does not detect impostors or man-in-the-middle attacks.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 6.5
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/28/4
    - https://access.redhat.com/security/cve/CVE-2025-4947
    - https://curl.se/docs/CVE-2025-4947.html
    - https://curl.se/docs/CVE-2025-4947.json
    - https://hackerone.com/reports/3150884
    - https://nvd.nist.gov/vuln/detail/CVE-2025-4947
    - https://www.cve.org/CVERecord?id=CVE-2025-4947
    PublishedDate: '2025-05-28T07:15:24.78Z'
    LastModifiedDate: '2025-05-28T15:01:30.72Z'
  - VulnerabilityID: CVE-2025-5025
    PkgID: curl-doc@8.13.0-r1
    PkgName: curl-doc
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl-doc@8.13.0-r1?arch=x86_64&distro=3.22.0_alpha20250108
      UID: d81fa5afdf86609d
    InstalledVersion: 8.13.0-r1
    FixedVersion: 8.14.0-r0
    Status: fixed
    Layer:
      Digest: sha256:1b256764d0e3457b2f7d15a1b7d9f50bc17b441f548cbfda2141f820f345589c
      DiffID: sha256:47f369694a4f622382553dd6634511eea449cb3e28b1b596262f88b91ef682c0
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-5025
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: libcurl: QUIC Certificate Pinning Bypass'
    Description: libcurl supports *pinning* of the server certificate public key for HTTPS transfers. Due to an omission, this check is not performed when connecting with QUIC for HTTP/3, when the TLS backend is wolfSSL. Documentation says the option works with wolfSSL, failing to specify that it does not for QUIC and HTTP/3. Since pinning makes the transfer succeed if the pin is fine, users could unwittingly connect to an impostor server without noticing.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.8
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/28/5
    - https://access.redhat.com/security/cve/CVE-2025-5025
    - https://curl.se/docs/CVE-2025-5025.html
    - https://curl.se/docs/CVE-2025-5025.json
    - https://hackerone.com/reports/3153497
    - https://nvd.nist.gov/vuln/detail/CVE-2025-5025
    - https://www.cve.org/CVERecord?id=CVE-2025-5025
    PublishedDate: '2025-05-28T07:15:24.91Z'
    LastModifiedDate: '2025-05-30T17:15:30.2Z'
  - VulnerabilityID: CVE-2025-4947
    PkgID: libcurl@8.13.0-r1
    PkgName: libcurl
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcurl@8.13.0-r1?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 209aff70b6f57dd2
    InstalledVersion: 8.13.0-r1
    FixedVersion: 8.14.0-r0
    Status: fixed
    Layer:
      Digest: sha256:1b256764d0e3457b2f7d15a1b7d9f50bc17b441f548cbfda2141f820f345589c
      DiffID: sha256:47f369694a4f622382553dd6634511eea449cb3e28b1b596262f88b91ef682c0
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4947
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'libcurl: curl: QUIC certificate check skip with wolfSSL'
    Description: libcurl accidentally skips the certificate verification for QUIC connections when connecting to a host specified as an IP address in the URL. Therefore, it does not detect impostors or man-in-the-middle attacks.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 6.5
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/28/4
    - https://access.redhat.com/security/cve/CVE-2025-4947
    - https://curl.se/docs/CVE-2025-4947.html
    - https://curl.se/docs/CVE-2025-4947.json
    - https://hackerone.com/reports/3150884
    - https://nvd.nist.gov/vuln/detail/CVE-2025-4947
    - https://www.cve.org/CVERecord?id=CVE-2025-4947
    PublishedDate: '2025-05-28T07:15:24.78Z'
    LastModifiedDate: '2025-05-28T15:01:30.72Z'
  - VulnerabilityID: CVE-2025-5025
    PkgID: libcurl@8.13.0-r1
    PkgName: libcurl
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcurl@8.13.0-r1?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 209aff70b6f57dd2
    InstalledVersion: 8.13.0-r1
    FixedVersion: 8.14.0-r0
    Status: fixed
    Layer:
      Digest: sha256:1b256764d0e3457b2f7d15a1b7d9f50bc17b441f548cbfda2141f820f345589c
      DiffID: sha256:47f369694a4f622382553dd6634511eea449cb3e28b1b596262f88b91ef682c0
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-5025
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: libcurl: QUIC Certificate Pinning Bypass'
    Description: libcurl supports *pinning* of the server certificate public key for HTTPS transfers. Due to an omission, this check is not performed when connecting with QUIC for HTTP/3, when the TLS backend is wolfSSL. Documentation says the option works with wolfSSL, failing to specify that it does not for QUIC and HTTP/3. Since pinning makes the transfer succeed if the pin is fine, users could unwittingly connect to an impostor server without noticing.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.8
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/28/5
    - https://access.redhat.com/security/cve/CVE-2025-5025
    - https://curl.se/docs/CVE-2025-5025.html
    - https://curl.se/docs/CVE-2025-5025.json
    - https://hackerone.com/reports/3153497
    - https://nvd.nist.gov/vuln/detail/CVE-2025-5025
    - https://www.cve.org/CVERecord?id=CVE-2025-5025
    PublishedDate: '2025-05-28T07:15:24.91Z'
    LastModifiedDate: '2025-05-30T17:15:30.2Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
