- Target: nmaguiar/netutils:build (alpine 3.20.3)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-52804
    PkgName: tornado
    PkgPath: opt/mitmproxy/lib/python3.12/site-packages/tornado-6.4.1.dist-info/METADATA
    PkgIdentifier:
      PURL: pkg:pypi/tornado@6.4.1
      UID: c01a8ef5d574c81
    InstalledVersion: 6.4.1
    FixedVersion: 6.4.2
    Status: fixed
    Layer:
      Digest: sha256:2a383569988c3c629d933aad126c36b0959d783b85c56ea3b8e0af3687cf5110
      DiffID: sha256:d647a7f3e19006b13c10de77ea97adf06e741857f2c3231900b952a245afed68
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-52804
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory pip
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip
    Title: Tornado is a Python web framework and asynchronous networking library. ...
    Description: Tornado is a Python web framework and asynchronous networking library. The algorithm used for parsing HTTP cookies in Tornado versions prior to 6.4.2 sometimes has quadratic complexity, leading to excessive CPU consumption when parsing maliciously-crafted cookie headers. This parsing occurs in the event loop thread and may block the processing of other requests. Version 6.4.2 fixes the issue.
    Severity: HIGH
    CweIDs:
    - CWE-400
    - CWE-770
    VendorSeverity:
      ghsa: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://github.com/advisories/GHSA-7pwv-g7hj-39pr
    - https://github.com/tornadoweb/tornado
    - https://github.com/tornadoweb/tornado/commit/d5ba4a1695fbf7c6a3e54313262639b198291533
    - https://github.com/tornadoweb/tornado/security/advisories/GHSA-8w49-h785-mj3c
    - https://nvd.nist.gov/vuln/detail/CVE-2024-52804
    PublishedDate: '2024-11-22T16:15:34.417Z'
    LastModifiedDate: '2024-11-22T16:15:34.417Z'
