- Target: nmaguiar/netutils:build-lite (alpine 3.24.0_alpha20260127)
  Class: os-pkgs
  Type: alpine
  Packages: []
  Vulnerabilities:
  - VulnerabilityID: CVE-2026-7598
    PkgID: libssh2@1.11.1-r1
    PkgName: libssh2
    PkgIdentifier:
      PURL: pkg:apk/alpine/libssh2@1.11.1-r1?arch=x86_64&distro=3.24.0_alpha20260127
      UID: 2ab480344db5ac8
    InstalledVersion: 1.11.1-r1
    FixedVersion: 1.11.1-r2
    Status: fixed
    Layer:
      Digest: sha256:6e55186ba32e570ba3edc391e8901f9a93ebff3170852a06dcd2cba18800a5f9
      DiffID: sha256:dd09171b064019c7e12a4a0c116230fd9d8fac5238270e47cf665345ee804203
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-7598
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:cef1a8281f88c5d4dcb2bde6202afbc03ee6ec7bea345fd8ca63908d2b2f3cf7
    Title: 'libssh2: integer overflow via large username or password arguments'
    Description: A security vulnerability has been detected in libssh2 up to 1.11.1. The impacted element is the function userauth_password of the file src/userauth.c. Such manipulation of the argument username_len/password_len leads to integer overflow. The attack may be launched remotely. The name of the patch is 256d04b60d80bf1190e96b0ad1e91b2174d744b1. A patch should be applied to remediate this issue.
    Severity: HIGH
    CweIDs:
    - CWE-189
    - CWE-190
    VendorSeverity:
      azure: 3
      redhat: 3
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H
        V3Score: 9.1
    References:
    - https://access.redhat.com/security/cve/CVE-2026-7598
    - https://github.com/libssh2/libssh2/
    - https://github.com/libssh2/libssh2/commit/256d04b60d80bf1190e96b0ad1e91b2174d744b1
    - https://github.com/libssh2/libssh2/pull/1858
    - https://nvd.nist.gov/vuln/detail/CVE-2026-7598
    - https://ubuntu.com/security/notices/USN-8309-1
    - https://vuldb.com/submit/805564
    - https://vuldb.com/vuln/360555
    - https://vuldb.com/vuln/360555/cti
    - https://www.cve.org/CVERecord?id=CVE-2026-7598
    PublishedDate: '2026-05-01T22:16:16.947Z'
    LastModifiedDate: '2026-05-07T01:47:08.857Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
  Packages: []
