FROM alpine:edge

RUN apk update && apk add --no-cache python3 py3-pip gcc g++ musl-dev libffi-dev openssl-dev python3-dev cargo rust make linux-headers bsd-compat-headers

RUN mkdir -p /opt/mitmproxy\
 && python3 -m venv /opt/mitmproxy\
 && . /opt/mitmproxy/bin/activate\
 && pip install mitmproxy

RUN mkdir -p /usr/local/bin && \
    cp /opt/mitmproxy/bin/mitm* /usr/bin/
