name: Build mitmproxy

on:
    workflow_dispatch:

jobs:
    build-x86:

        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: build
          run : |
            docker system prune -f
            rm -rf mitmproxy
            docker build --no-cache -f Dockerfile.mitm -o mitmproxy .

        - name: Cache mitmproxy save
          uses: actions/cache/save@v3
          with:
            key : mitmproxy-${{ runner.arch }}
            path: |
              mitmproxy

    build-arm64:

        runs-on: ubuntu-24.04-arm
    
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: build
          run : |
            docker system prune -f
            rm -rf mitmproxy
            docker build --no-cache -f Dockerfile.mitm -o mitmproxy .

        - name: Cache mitmproxy save
          uses: actions/cache/save@v3
          with:
            key : mitmproxy-${{ runner.arch }}
            path: |
              mitmproxy
