name: Scan Versions

on:
  workflow_dispatch:
  schedule:
  - cron: '37 8 * * *'

jobs:
  Scan-Versions:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Scan version
    steps      :
    - uses: actions/checkout@v4
      name: Checkout

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-nightly
        path: /tmp/oaf

    - name: Get versions build
      run : |
        docker run --rm nmaguiar/netutils:build /openaf/ojob /openaf/ojobs/softVersions.yaml -json > .github/softVersions-build.json

    - name: Get versions build lite
      run : |
        docker run --rm nmaguiar/netutils:build-lite /openaf/ojob /openaf/ojobs/softVersions.yaml -json > .github/softVersions-build-lite.json

    - name: Get versions latest
      run : |
        docker run --rm nmaguiar/netutils:latest /openaf/ojob /openaf/ojobs/softVersions.yaml -json > .github/softVersions-latest.json

    # - name: Get versions latest lite
    #   run : |
    #     docker run --rm nmaguiar/netutils:lite /openaf/ojob /openaf/ojobs/softVersions.yaml -json > .github/softVersions-latest-lite.json

    - uses: openaf/ojob-action@v7
      name: Update files
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="update\ versions\ {{date}}/{{time}}" title="Update\ versions" paths=.github/'
        dist: 'nightly'